plugin:
    name: 'grcote7.movies::lang.plugin.name'
    description: 'grcote7.movies::lang.plugin.description'
    author: Grcote7
    icon: oc-icon-video-camera
    homepage: ''
navigation:
    main-menu-item:
        label: 'grcote7.movies::lang.plugin.name'
        url: grcote7/movies/movies
        icon: icon-video-camera
        permissions:
            - manage_movies
        sideMenu:
            side-menu-item:
                label: Genres
                url: grcote7/movies/genres
                icon: icon-tag
                permissions:
                    - manage_genres
            side-menu-item2:
                label: Actors
                url: grcote7/movies/actors
                icon: icon-user
            side-menu-item3:
                label: Tags
                url: grcote7/movies/tags
                icon: icon-tag
permissions:
    manage_movies:
        tab: 'grcote7.movies::lang.plugin.name'
        label: 'Manage Movies'
    manage_genres:
        tab: 'grcote7.movies::lang.plugin.name'
        label: 'Manage Genres'
    delete_movies:
        tab: 'grcote7.movies::lang.plugin.name'
        label: 'Delete Movies'
